In [1]:
import pandas as pd

# place any csv file in this code
data = pd.read_csv("Trans_Course_Demos.csv")
data

,PIF ID,ER5,PIFDATE,Date created,City,State,Registration Zip,Years in HIV Care,Ryan White Funded,PIF3,...,PIF14,PIF15,PIF16,PIF17,PIF18,PIF19,PIF20,PIF21,PIF22,PIF23
0,moontreemidwifery@gmail.com,21040716,10/29/2021 19:46:08,10/29/2021 19:44:07,NaN,NaN,NaN,NaN,No,NaN,...,12.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,allie.evans@hsc.utah.edu,21040716,11/03/2021 19:15:49,11/03/2021 19:12:02,Salt Lake City,UT,NaN,NaN,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
col_name = []
col_data_arr = []

# this code finds all of the columns that have object datatypes in the data dataframe and then removes them 
# from the data dataframe
for i in range(len(data.columns)):
    if data.dtypes[i] == "object":
        col_data = data[data.columns[i]]
        col_data_arr.append(col_data)
        col_name.append(data.columns[i])

print(col_name)      
data = data.drop(col_name, axis = 1)

# Following removal of the columns with an object datatype, the object datatype columns
# are readded to the end of the dataframe
for i in range(len(col_name)):
    data[col_name[i]] = col_data_arr[i]

# This adds the keyword Categ to the end of the column names that have an object dtype
for i in range(len(data.columns)):
    if data.dtypes[i] == "object" and i != 0:
        data = data.rename(columns={data.columns[i]: data.columns[i].replace(" ", "")+"Categ"})
    elif i == 0:
        data = data.rename(columns={data.columns[i]: "ID"})
    else:
        data = data.rename(columns={data.columns[i]: data.columns[i].replace(" ", "")})
data

['PIF ID', 'PIFDATE', 'Date created', 'City', 'State', 'Ryan White Funded', 'PIF9', 'PIF4OTH', 'PIF Created DATE', 'Local Partner Site', 'Eval complete', 'Attended']

,ID,RegistrationZip,YearsinHIVCare,PIF3,PIF4,PIF5,PIF601,PIF602,PIF603,PIF604,...,DatecreatedCateg,CityCateg,StateCateg,RyanWhiteFundedCateg,PIF9Categ,PIF4OTHCateg,PIFCreatedDATECateg,LocalPartnerSiteCateg,EvalcompleteCateg,AttendedCateg
0,21040716,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,10/29/2021 19:44:07,NaN,NaN,No,NaN,NaN,10/29/2021 19:45:54,Utah AETC,No,No
1,21040716,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,11/03/2021 19:12:02,Salt Lake City,UT,No,University of Utah Health,Clinical Education Outreach Nurse,11/03/2021 19:15:22,Utah AETC,No,No

In [3]:
data.columns

Index(['ID', 'RegistrationZip', 'YearsinHIVCare', 'PIF3', 'PIF4', 'PIF5',
       'PIF601', 'PIF602', 'PIF603', 'PIF604', 'PIF605', 'PIF7', 'PIF801',
       'PIF802', 'PIF803', 'PIF1001', 'PIF1002', 'PIF1003', 'PIF1004',
       'PIF1005', 'PIF1006', 'PIF1007', 'PIF1008', 'PIF1009', 'PIF1010',
       'PIF1011', 'PIF1012', 'PIF1013', 'PIF3OTH', 'PIF3OTH2', 'PIF1014',
       'PIF1015', 'PIF1016', 'PIF1017', 'PIF1018', 'PIF1019', 'PIF1020',
       'PIF1021', 'PIF1022', 'PIF1023', 'PIF11', 'PIF12', 'PIF13', 'PIF14',
       'PIF15', 'PIF16', 'PIF17', 'PIF18', 'PIF19', 'PIF20', 'PIF21', 'PIF22',
       'PIF23', 'PIFIDCateg', 'PIFDATECateg', 'DatecreatedCateg', 'CityCateg',
       'StateCateg', 'RyanWhiteFundedCateg', 'PIF9Categ', 'PIF4OTHCateg',
       'PIFCreatedDATECateg', 'LocalPartnerSiteCateg', 'EvalcompleteCateg',
       'AttendedCateg'],
      dtype='object')

In [4]:
# this removes spaces and special characters from the categories
for i in range(len(data.columns)):
    if data.dtypes[i] == "object" and "DATE" in data.columns[i]:
        for k in range(len(data)):
            data[data.columns[i]][k] = "Date" + data[data.columns[i]][k][0:10]
            data[data.columns[i]][k] = data[data.columns[i]][k].replace("/", "-")
            data[data.columns[i]][k] = data[data.columns[i]][k].replace(":", "")
            
    elif data.dtypes[i] == "object" and "Date" not in data.columns[i]:
        
        for k in range(len(data)):
            if type(data[data.columns[i]][k]) == str:
                data[data.columns[i]][k] = data[data.columns[i]][k].replace("/", "-")
                data[data.columns[i]][k] = data[data.columns[i]][k].replace(".", "dot")
                data[data.columns[i]][k] = data[data.columns[i]][k].replace("@", "at")
                data[data.columns[i]][k] = data[data.columns[i]][k].replace(" ", "")
                data[data.columns[i]][k] = data[data.columns[i]][k].replace(":", "")
    
    # this changes the date format into a compatible date format     
    elif data.dtypes[i] == "object" and "Date" in data.columns[i]:
        for k in range(len(data)):
            data[data.columns[i]][k] = "Date" + data[data.columns[i]][k][0:10]
            data[data.columns[i]][k] = data[data.columns[i]][k].replace("/", "-")

data

<ipython-input-4-903dc5cec698>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[data.columns[i]][k] = data[data.columns[i]][k].replace("/", "-")
<ipython-input-4-903dc5cec698>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[data.columns[i]][k] = data[data.columns[i]][k].replace(".", "dot")
<ipython-input-4-903dc5cec698>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[data.columns[i]][k] = data[data.columns[i]][k].replace("@", "at")
<ipython-input-4-903dc5cec698>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[data.columns[i]][k] = data[data.columns[i]][k].replace(" ", "")
<ipython-input-4-903dc5cec698>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[data.columns[i]][k] = data[data.columns[i]][k].replace(":", "")
<ipython-input-4-903dc5cec698>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[data.columns[i]][k] = "Date" + data[data.columns[i]][k][0:10]
<ipython-input-4-903dc5cec698>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[data.columns[i]][k] = data[data.columns[i]][k].replace("/", "-")
<ipython-input-4-903dc5cec698>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[data.columns[i]][k] = data[data.columns[i]][k].replace(":", "")
<ipython-input-4-903dc5cec698>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[data.columns[i]][k] = "Date" + data[data.columns[i]][k][0:10]
<ipython-input-4-903dc5cec698>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[data.columns[i]][k] = data[data.columns[i]][k].replace("/", "-")

,ID,RegistrationZip,YearsinHIVCare,PIF3,PIF4,PIF5,PIF601,PIF602,PIF603,PIF604,...,DatecreatedCateg,CityCateg,StateCateg,RyanWhiteFundedCateg,PIF9Categ,PIF4OTHCateg,PIFCreatedDATECateg,LocalPartnerSiteCateg,EvalcompleteCateg,AttendedCateg
0,21040716,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,Date10-29-2021,NaN,NaN,No,NaN,NaN,Date10-29-2021,UtahAETC,No,No
1,21040716,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,Date11-03-2021,SaltLakeCity,UT,No,UniversityofUtahHealth,ClinicalEducationOutreachNurse,Date11-03-2021,UtahAETC,No,No

In [5]:
data['ID'] = 'id' + data['ID'].astype(str)

In [6]:
data.to_csv("AlteredData.csv", index = False)